import assert from 'node:assert/strict';
import {createCaptionTone} from '../dist/captions.js';
const variables = {};
const tone = createCaptionTone({renderer:null, el:{style:{setProperty:(k,v)=>variables[k]=v}}});
const settle = seconds => { for(let i=0;i<seconds*60;i++) tone.update(1/60); };
const measured = (lo,hi) => Object.assign(tone.S,{source:'frame',lo,hi,lum:(lo+hi)/2});
let passed=0;
const check=(name,value)=>{assert.ok(value,name);passed++;console.log('PASS',name);};
measured(.01,.03);settle(3);
check('dark scene uses light text without backing',tone.state.mode==='light'&&tone.state.scrim===0);
measured(.0172,.4387);settle(3);
check('measured flashlight-wall fixture below 2:1 gets useful backing',tone.state.contrast<2&&tone.state.scrim>=.5);
check('backing is a transparent-edge radial treatment, not a box',variables['--cap-scrim'].startsWith('radial-gradient(')&&variables['--cap-scrim'].endsWith(',0))'));
measured(.01,(.906+.05)/1.999-.05);settle(3);
check('just below 2:1 also receives backing',tone.state.scrim>=.5);
measured(.01,.03);settle(4);
check('backing fades away again in clear darkness',tone.state.scrim===0&&variables['--cap-scrim']==='none');
measured(.7,.8);settle(4);
check('bright scene changes to dark text without backing',tone.state.mode==='dark'&&tone.state.scrim===0);
console.log(JSON.stringify({passed}));
