// Run only the additional Astra checks while refining their concrete failures.
import fs from 'node:fs';import http from 'node:http';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {runSceneChecks} from './polish-scenes.mjs';
const require=createRequire(import.meta.url);let pw;try{pw=require('playwright');}catch{pw=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');}
const out=path.resolve(process.env.QA_OUTPUT||'docs/qa'),root=path.resolve('dist');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const p=path.join(root,req.url.split('?')[0]);try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await pw.chromium.launch({executablePath:process.env.BROWSER_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--single-process','--no-zygote','--in-process-gpu']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],checks=[],frames=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const state=()=>page.evaluate(()=>lastLight.state);const check=(n,v)=>{assert.ok(v,n);checks.push(n);console.log('PASS',n);};
const snap=async(name)=>{const info=await page.evaluate(()=>{for(const id of ['title-card','objective','objective-note','ending','prompt','subtitle','reflection','fade'])for(const a of document.getElementById(id)?.getAnimations()||[])try{a.finish();}catch{}return {...lastLight.render()};});await page.screenshot({path:path.join(out,name+'.jpg'),type:'jpeg',quality:90});frames.push({name,...info});console.log('Captured',name,JSON.stringify(info));};
const camAt=async(name,t)=>{await page.evaluate(t=>{const L=lastLight,h=L.world.homes[t.house||t.garage],o=t.garage?[h.garageInfo.x,h.garageInfo.front]:[0,0],a=h.toWorld(o[0]+t.from[0],o[1]+t.from[2]),b=h.toWorld(o[0]+t.at[0],o[1]+t.at[2]);L.camera.position.set(a.x,a.ground+t.from[1],a.z);L.camera.lookAt(b.x,b.ground+t.at[1],b.z);L.camera.updateMatrixWorld();},t);await snap(name);};
try{await page.goto(`http://127.0.0.1:${server.address().port}/index.html?qa`);await page.waitForFunction(()=>window.lastLight);await page.click('#start');await page.keyboard.press('m');await runSceneChecks({page,snap,check,camAt,state});check('no JS or shader errors',errors.length===0);fs.writeFileSync(path.join(out,'scene-report.json'),JSON.stringify({checks,passed:checks.length,frames,errors},null,2));}
catch(e){await snap('astra-failure');console.error('STATE',JSON.stringify(await state()));console.error('ERRORS',errors);throw e;}finally{await browser.close();server.close();}
